SCREEN_WIDTH = 800
SCREEN_HEIGHT = 800

FPS = 60.0

CURRENT_MAP = None
TILE_GRID = 10
TILE_WIDTH = SCREEN_WIDTH/TILE_GRID
TILE_HEIGHT = SCREEN_HEIGHT/TILE_GRID

MAIN_CAMERA = None
VISION_DISTANCE = 2

PLAYER_SIZE = 50
PLAYER_SPEED = 200